model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/f1" # name of the logged metric which determines when model is improving
  mode: "max" # "max" means higher metric value is better, can be also "min"
  save_top_k: 1 # save k best models (determined by above metric)
  verbose: True
  save_last: False # additionaly always save model from last epoch
  save_weights_only: True
  dirpath: "checkpoints/"
  filename: "epoch_{epoch}-{val/f1:.2f}"
  auto_insert_metric_name: False

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar

upload_code_as_artifact:
  _target_: pytorch_lightning.callbacks.UploadCodeAsArtifact

learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "step"
